version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workfusion_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=workfusion
      - DB_USERNAME=workfusion
      - DB_PASSWORD=workfusion

  db:
    image: mysql:8
    container_name: workfusion_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: workfusion
      MYSQL_USER: workfusion
      MYSQL_PASSWORD: workfusion
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: